# Turns the test methods in a managed assembly into ctest tests.
#
# CMakeLists.txt in this directory generates an _include.cmake per suite that
# includes this file and calls the function below, which runs the runner's
# --list and writes add_test() calls out to CTEST_FILE.  That happens when ctest
# starts rather than at configure time, so a method added to a .cs file is a new
# test after a build, with no cmake step in between.
#
# It is a file of its own because ctest reads it long after the configure that
# wrote the caller.
#
# Listing needs a working runtime, which here is the thing under test.  A run
# that fails registers one failing test carrying the error instead of stopping
# ctest: a suite that cannot enumerate itself has to stay visible, and it must
# not take the suites that would have passed down with it.

cmake_minimum_required(VERSION 3.16)

# mono_discover_test_methods_impl(
#     CMAKE_EXE <cmake> RUNNER <exe> ASSEMBLY <dll> CTEST_FILE <out>
#     NAME_PREFIX <str> NAME_SUFFIX <str> WORKING_DIR <dir> TIMEOUT <seconds>
#     [PROPERTIES <prop>;<value>...] [ENVIRONMENT <VAR=value>...]
#     [XFAIL <Class:method>...])
#
# cmake is named rather than taken from CMAKE_COMMAND, which ctest leaves unset
# in the context this runs in.
function(mono_discover_test_methods_impl)
  cmake_parse_arguments(ARG ""
    "CMAKE_EXE;RUNNER;ASSEMBLY;CTEST_FILE;NAME_PREFIX;NAME_SUFFIX;WORKING_DIR;TIMEOUT"
    "PROPERTIES;ENVIRONMENT;XFAIL" ${ARGN})

  # Every generated token is bracket-quoted, so a property value with spaces in
  # it -- SKIP_REGULAR_EXPRESSION, mostly -- survives being written out and read
  # back.
  set(_props "")
  foreach(_p IN LISTS ARG_PROPERTIES)
    string(APPEND _props " [==[${_p}]==]")
  endforeach()

  set(_prefix "")
  set(_env "")
  if(ARG_ENVIRONMENT)
    set(_prefix "${ARG_CMAKE_EXE}" -E env ${ARG_ENVIRONMENT})
    set(_env " [==[${ARG_CMAKE_EXE}]==] [==[-E]==] [==[env]==]")
    foreach(_e IN LISTS ARG_ENVIRONMENT)
      string(APPEND _env " [==[${_e}]==]")
    endforeach()
  endif()

  # The listing runs in the environment the cases get, so it sees the runtime
  # they will.
  execute_process(
    COMMAND ${_prefix} "${ARG_RUNNER}" --list "${ARG_ASSEMBLY}"
    WORKING_DIRECTORY "${ARG_WORKING_DIR}"
    TIMEOUT ${ARG_TIMEOUT}
    OUTPUT_VARIABLE _listing
    ERROR_VARIABLE _errors
    RESULT_VARIABLE _result)

  set(_text "# Generated by mono/interp/tests/discover.cmake -- do not edit.\n")

  if(NOT _result EQUAL 0)
    set(_name "${ARG_NAME_PREFIX}!listing${ARG_NAME_SUFFIX}")
    string(REGEX REPLACE "[\r\n]+" " " _why "${_result}: ${_errors}")
    string(APPEND _text
      "add_test([==[${_name}]==] [==[${ARG_CMAKE_EXE}]==] [==[-E]==] [==[false]==])\n"
      "set_tests_properties([==[${_name}]==] PROPERTIES${_props})\n"
      "# ${ARG_ASSEMBLY}: ${_why}\n")
    file(WRITE "${ARG_CTEST_FILE}" "${_text}")
    message(WARNING "cannot list ${ARG_ASSEMBLY}: ${_why}")
    return()
  endif()

  string(REPLACE "\n" ";" _lines "${_listing}")
  foreach(_line IN LISTS _lines)
    string(STRIP "${_line}" _test)
    if(_test STREQUAL "")
      continue()
    endif()

    set(_name "${ARG_NAME_PREFIX}${_test}${ARG_NAME_SUFFIX}")
    set(_xfail "")
    if("${_test}" IN_LIST ARG_XFAIL)
      set(_xfail " WILL_FAIL [==[TRUE]==]")
    endif()
    string(APPEND _text
      "add_test([==[${_name}]==]${_env} [==[${ARG_RUNNER}]==]"
      " [==[${ARG_ASSEMBLY}]==] [==[${_test}]==])\n"
      "set_tests_properties([==[${_name}]==] PROPERTIES"
      " WORKING_DIRECTORY [==[${ARG_WORKING_DIR}]==]${_props}${_xfail})\n")
  endforeach()

  file(WRITE "${ARG_CTEST_FILE}" "${_text}")
endfunction()
