# Test corpus for mono/tests -- the data half of this directory's build, kept
# apart from CMakeLists.txt because the lists are long and they change
# independently of the rules.
#
# These are the amd64/Linux/JIT lists. Tests that only ever applied to another
# architecture, to Windows or Darwin, or to one of the AOT profiles are not
# here -- the same scope this build applies everywhere else.

# Ordinary C# tests: one assembly each, compiled against TestDriver.dll.
set(MONO_TESTS_CS_SRC
  cast-cache.cs
  cast-subtype.cs
  alloc-elide.cs
  generic-unloading-sub.2.cs
  create-instance.cs
  bug-2907.cs
  array-coop-bigvt.cs
  array-coop-int.cs
  array-coop-smallvt.cs
  array-12193.cs
  array-init.cs
  arraylist.cs
  assembly-load-remap.cs
  assembly-load-bytes.cs
  assembly-load-stress.cs
  assembly-loadfile.cs
  assembly-loadfrom.cs
  assembly-load-bytes-bindingredirect.cs
  assembly-loadfile-bindingredirect.cs
  assembly-loadfrom-bindingredirect.cs
  assembly-loadfrom-simplename.cs
  assembly-refonly-load-bytes-bindingredirect.cs
  assemblyresolve_event.cs
  assemblyresolve_event3.cs
  assemblyresolve_event4.cs
  assemblyresolve_event5.cs
  assemblyresolve_event6.cs
  assemblyresolve_event7.cs
  checked.cs
  char-isnumber.cs
  field-layout.cs
  pack-layout.cs
  pack-bug.cs
  hash-table.cs
  test-ops.cs
  obj.cs
  test-dup-mp.cs
  string.cs
  stringbuilder.cs
  switch.cs
  outparm.cs
  delegate.cs
  bitconverter.cs
  exception.cs
  exception2.cs
  exception3.cs
  exception4.cs
  exception5.cs
  exception6.cs
  exception7.cs
  exception8.cs
  exception10.cs
  exception11.cs
  exception12.cs
  exception13.cs
  exception14.cs
  exception15.cs
  exception16.cs
  exception17.cs
  exception18.cs
  exception-invokes.cs
  merp-json-valid.cs
  merp-crash-test.cs
  dump-state-json-valid.cs
  interp-frame-native-offset.cs
  exception19.cs
  exception20.cs
  exception21.cs
  typeload-unaligned.cs
  struct.cs
  valuetype-gettype.cs
  typeof-ptr.cs
  static-constructor.cs
  pinvoke.cs
  pinvoke-utf8.cs
  pinvoke-handleref.cs
  pinvoke3.cs
  pinvoke11.cs
  pinvoke13.cs
  pinvoke17.cs
  pinvoke-detach-1.cs
  invoke.cs
  invoke2.cs
  runtime-invoke.cs
  invoke-string-ctors.cs
  reinit.cs
  box.cs
  array.cs
  enum.cs
  enum2.cs
  enum-intrins.cs
  property.cs
  enumcast.cs
  assignable-tests.cs
  array-cast.cs
  array-subtype-attr.cs
  cattr-compile.cs
  cattr-field.cs
  cattr-object.cs
  custom-attr.cs
  double-cast.cs
  newobj-valuetype.cs
  arraylist-clone.cs
  setenv.cs
  vtype.cs
  isvaluetype.cs
  iface6.cs
  iface7.cs
  ipaddress.cs
  array-vt.cs
  interface1.cs
  reflection-enum.cs
  reflection-prop.cs
  reflection4.cs
  reflection5.cs
  reflection-const-field.cs
  many-locals.cs
  string-compare.cs
  test-prime.cs
  test-tls.cs
  params.cs
  reflection.cs
  interface.cs
  interface-2.cs
  dim-generic.cs
  dim-issue-18917.cs
  iface.cs
  iface2.cs
  iface3.cs
  iface4.cs
  iface-large.cs
  iface-contravariant1.cs
  imt-variance-fallback.cs
  vtable-slot-targets.cs
  virtual-method.cs
  intptrcast.cs
  indexer.cs
  stream.cs
  console.cs
  shift.cs
  jit-int.cs
  jit-uint.cs
  jit-long.cs
  long.cs
  jit-ulong.cs
  jit-float.cs
  pop.cs
  time.cs
  pointer.cs
  pointer-this.cs
  hashcode.cs
  delegate1.cs
  delegate2.cs
  delegate3.cs
  delegate5.cs
  delegate6.cs
  delegate7.cs
  delegate8.cs
  delegate10.cs
  delegate11.cs
  delegate12.cs
  delegate13.cs
  delegate14.cs
  delegate15.cs
  delegate16.cs
  delegate17.cs
  delegate18.cs
  largeexp.cs
  largeexp2.cs
  marshalbyref1.cs
  static-ctor.cs
  inctest.cs
  bound.cs
  array-invoke.cs
  test-arr.cs
  decimal.cs
  decimal-array.cs
  vtype-return-in-try.cs
  marshal.cs
  marshal1.cs
  marshal2.cs
  marshal3.cs
  marshal5.cs
  marshal6.cs
  marshal7.cs
  marshal8.cs
  marshal9.cs
  marshalbool.cs
  fixed-buffer-copy.cs
  test-byval-in-struct.cs
  thread.cs
  thread5.cs
  thread-static.cs
  thread-static-init.cs
  context-static.cs
  float-pop.cs
  interfacecast.cs
  array3.cs
  classinit.cs
  classinit2.cs
  classinit3.cs
  synchronized.cs
  async_read.cs
  threadpool.cs
  threadpool1.cs
  threadpool-exceptions1.cs
  threadpool-exceptions3.cs
  threadpool-exceptions4.cs
  threadpool-exceptions6.cs
  base-definition.cs
  bug-27420.cs
  bug-46781.cs
  bug-42136.cs
  bug-59286.cs
  bug-70561.cs
  bug-78311.cs
  bug-78653.cs
  bug-78656.cs
  bug-77127.cs
  bug-323114.cs
  bug-Xamarin-5278.cs
  interlocked.cs
  interp-entries.cs
  interp-calls-compiled.cs
  interp-tier1-promotion.cs
  interp-native-detour.cs
  trivial-inline.cs
  tier2-inline-override.cs
  override-basic.cs
  override-generic.cs
  override-declared.cs
  override-icall.cs
  override-copies.cs
  callvirt-static.cs
  interp-float-to-int.cs
  interp-threadstatic-cctor.cs
  interp-array-set-typecheck.cs
  volatile-prefix.cs
  delegate-async-exit.cs
  delegate-delegate-exit.cs
  delegate-exit.cs
  delegate-disposed-hashcode.cs
  finalizer-abort.cs
  finalizer-exception.cs
  finalizer-exit.cs
  finalizer-thread.cs
  handle-stack-abort.cs
  main-exit.cs
  main-returns-abort-resetabort.cs
  main-returns-background-abort-resetabort.cs
  main-returns-background-resetabort.cs
  main-returns-background.cs
  main-returns-background-change.cs
  main-returns.cs
  subthread-exit.cs
  desweak.cs
  exists.cs
  handleref.cs
  install_eh_callback.cs
  dbnull-missing.cs
  test-type-ctor.cs
  soft-float-tests.cs
  thread-exit.cs
  finalize-parent.cs
  interlocked-2.2.cs
  pinvoke-2.2.cs
  bug-78431.2.cs
  bug-79684.2.cs
  catch-generics.2.cs
  event-get.2.cs
  safehandle.2.cs
  module-cctor-loader.2.cs
  generics-invoke-byref.2.cs
  generic-signature-compare.2.cs
  generics-sharing.2.cs
  shared-generic-methods.2.cs
  shared-generic-synchronized.2.cs
  generic-inlining.2.cs
  generic-initobj.2.cs
  generic-delegate.2.cs
  generic-sizeof.2.cs
  generic-virtual.2.cs
  generic-interface-methods.2.cs
  generic-array-type.2.cs
  generic-method-patching.2.cs
  generic-static-methods.2.cs
  generic-null-call.2.cs
  generic-special.2.cs
  generic-special2.2.cs
  generic-exceptions.2.cs
  generic-virtual2.2.cs
  generic-valuetype-interface.2.cs
  generic-getgenericarguments.2.cs
  generic-synchronized.2.cs
  generic-delegate-ctor.2.cs
  generic-array-iface-set.2.cs
  generic-typedef.2.cs
  bug-431413.2.cs
  bug-459285.2.cs
  generic-virtual-invoke.2.cs
  bug-461198.2.cs
  generic-sealed-virtual.2.cs
  generic-system-arrays.2.cs
  generic-stack-traces.2.cs
  generic-stack-traces2.2.cs
  bug-472600.2.cs
  recursive-generics.2.cs
  recursive-generics.3.cs
  bug-473482.2.cs
  bug-473999.2.cs
  bug-479763.2.cs
  bug-616463.cs
  bug-80392.2.cs
  bug-82194.2.cs
  anonarray.2.cs
  ienumerator-interfaces.2.cs
  array-enumerator-ifaces.2.cs
  generic_type_definition_encoding.2.cs
  bug-333798.2.cs
  bug-348522.2.cs
  bug-340662_bug.cs
  bug-325283.2.cs
  thunks.cs
  winx64structs.cs
  nullable_boxing.2.cs
  constrained-nullable-receiver.cs
  valuetype-equals.cs
  custom-modifiers.2.cs
  custom-modifiers-inheritance.cs
  bug-382986.cs
  test-inline-call-stack.cs
  bug-324535.cs
  modules.cs
  bug-81673.cs
  bug-81691.cs
  bug-415577.cs
  filter-stack.cs
  stack-frames-entry-thunk.cs
  vararg.cs
  vararg2.cs
  vararg4.cs
  bug-461867.cs
  bug-461941.cs
  bug-461261.cs
  bug-400716.cs
  bug-459094.cs
  bug-467456.cs
  bug-508538.cs
  bug-472692.2.cs
  gchandles.cs
  interlocked-3.cs
  interlocked-4.2.cs
  w32message.cs
  gc-altstack.cs
  large-gc-bitmap.cs
  bug-561239.cs
  bug-562150.cs
  bug-599469.cs
  monitor-resurrection.cs
  monitor-wait-abort.cs
  monitor-abort.cs
  bug-666008.cs
  bug-685908.cs
  sgen-long-vtype.cs
  delegate-invoke.cs
  delegate-invoke-shapes.cs
  delegate-prop.cs
  bug-696593.cs
  bug-705140.cs
  bug-1147.cs
  mono-path.cs
  bug-bxc-795.cs
  bug-3903.cs
  async-with-cb-throws.cs
  bug-6148.cs
  bug-10127.cs
  bug-18026.cs
  allow-synchronous-major.cs
  block_guard_restore_alignment_on_exit.cs
  thread_static_gc_layout.cs
  sleep.cs
  bug-27147.cs
  bug-30085.cs
  bug-17537.cs
  pinvoke_ppcc.cs
  pinvoke_ppcs.cs
  pinvoke_ppci.cs
  pinvoke_ppcf.cs
  pinvoke_ppcd.cs
  bug-29585.cs
  priority.cs
  abort-cctor.cs
  cctor-init-once.cs
  cctor-init-throws.cs
  cctor-init-eh.cs
  cctor-init-loop.cs
  cctor-init-race.cs
  abort-try-holes.cs
  abort-tests.cs
  thread-native-exit.cs
  reference-loader.cs
  thread-suspend-suspended.cs
  thread-suspend-selfsuspended.cs
  remoting4.cs
  remoting1.cs
  remoting2.cs
  remoting3.cs
  remoting5.cs
  appdomain.cs
  appdomain-client.cs
  appdomain-unload.cs
  appdomain-async-invoke.cs
  appdomain-thread-abort.cs
  appdomain1.cs
  appdomain2.cs
  appdomain-exit.cs
  appdomain-serialize-exception.cs
  assemblyresolve_event2.2.cs
  appdomain-unload-callback.cs
  appdomain-unload-doesnot-raise-pending-events.cs
  appdomain-unload-asmload.cs
  appdomain-unload-exception.cs
  unload-appdomain-on-shutdown.cs
  appdomain-marshalbyref-assemblyload.cs
  bug-47295.cs
  loader.cs
  pinvoke2.cs
  generic-type-builder.2.cs
  dynamic-generic-size.cs
  cominterop.cs
  dynamic-method-access.2.cs
  dynamic-method-finalize.2.cs
  dynamic-method-stack-traces.cs
  generic_type_definition.2.cs
  bug-333798-tb.2.cs
  bug-335131.2.cs
  bug-322722_patch_bx.2.cs
  bug-322722_dyn_method_throw.2.cs
  bug-389886-2.cs
  bug-349190.2.cs
  bug-389886-sre-generic-interface-instances.cs
  bug-462592.cs
  bug-575941.cs
  bug-389886-3.cs
  constant-division.cs
  dynamic-method-resurrection.cs
  bug-80307.cs
  assembly_append_ordering.cs
  bug-544446.cs
  bug-36848.cs
  generic-marshalbyref.2.cs
  stackframes-async.2.cs
  transparentproxy.cs
  proxy-cast-cache.cs
  bug-48015.cs
  delegate9.cs
  marshal-valuetypes.cs
  xdomain-threads.cs
  monitor.cs
  generic-xdomain.2.cs
  threadpool-exceptions7.cs
  threadpool-exceptions8.cs
  cross-domain.cs
  generic-unloading.2.cs
  namedmutex-destroy-race.cs
  thread6.cs
  thread7.cs
  appdomain-threadpool-unload.cs
  process-unref-race.cs
  bug-46661.cs
  w32message.cs
  runtime-invoke.gen.cs
  imt_big_iface_test.cs
  bug-58782-plain-throw.cs
  bug-58782-capture-and-throw.cs
  recursive-struct-arrays.cs
  struct-explicit-layout.cs
  struct-static.cs
  bug-59281.cs
  init_array_with_lazy_type.cs
  weak-fields.cs
  threads-leak.cs
  threads-init.cs
  bug-60848.cs
  bug-59400.cs
  tailcall-generic-cast-cs.cs
  tailcall-interface.cs
  bug-60843.cs
  nested_type_visibility.cs
  dynamic-method-churn.cs
  dynamic-method-delegate.cs
  dynamic-method-gc-in-body.cs
  dynamic-method-gc-in-frame.cs
  interp-stack-gc-root.cs
  interp-jit-delegate.cs
  verbose.cs
  generic-unmanaged-constraint.cs
  bug-10834.cs
  bug-10837.cs
  bug-gh-9507.cs
  async-generic-enum.cs
  null-blob-main.cs
  last-error.cs
  rgctx-thread-static.cs
  ccw-class-iface.cs
  ccw-array-return.cs
  bug-gh-17285.cs
  roslyn-bug-19038.cs
  sizeof-empty-structs.cs
  async-exc-compilation.cs
  finally_guard.cs
  finally_block_ending_in_dead_bb.cs
  finally-throwing-handler.cs
  finally-gc-move.cs
  finally-nested-resume.cs
  bug-60862.cs
  bug-unity-1.cs
)

# Tests written directly in IL, assembled with ilasm.
set(MONO_TESTS_IL_SRC
  float-stack-precision.il
  tailcall/2.il
  tailcall/3.il
  tailcall/4.il
  tailcall/fsharp-deeptail.il
  tailcall/fsharp-shallowtail.il
  tailcall/fsharp-shallownotail.il
  tailcall/fsharp-deeptail/Seq.filter-length1.il
  tailcall/fsharp-deeptail/Seq.filter-length2.il
  tailcall/fsharp-deeptail/Seq.filter-length3.il
  tailcall/fsharp-deeptail/StaticTailCallLoop_DateTime_.il
  tailcall/fsharp-deeptail/StaticTailCallLoop_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_DateTime_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_DateTime_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_DateTime_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_DateTime_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_DatstringeTime_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_byte_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_byte_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_byte_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_byte_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_int_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_int_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_int_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_int_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_string_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_string_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractClass_string_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_DateTime_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_DateTime_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_DateTime_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_DateTime_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_DatstringeTime_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_byte_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_byte_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_byte_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_byte_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_int_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_int_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_int_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_int_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_string_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_string_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethodAbstractInterface_string_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_DateTime_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_DateTime_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_DateTime_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_DateTime_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_byte_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_byte_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_byte_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_byte_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_int_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_int_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_int_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_int_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_string_.Method1_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_string_.Method1_byte_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_string_.Method1_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClassAndMethod_string_.Method1_string_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClass_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClass_int_.il
  tailcall/fsharp-deeptail/TailCallLoopGenericClass_string_.il
  tailcall/fsharp-deeptail/TailCallLoop_DateTime_.il
  tailcall/fsharp-deeptail/TailCallLoop_int_.il
  tailcall/fsharp-deeptail/mutualTail1IsEven.il
  tailcall/fsharp-deeptail/mutualTail1IsOdd.il
  tailcall/fsharp-deeptail/simpleTail1.il
  tailcall/fsharp-deeptail/simpleTail2.il
  gptail1.il
  itail1.il
  itaili1.il
  ivtail1.il
  sirtail1.il
  sitail1.il
  srtail1.il
  stail1.il
  tail1.il
  taili1.il
  vtail1.il
  tailcall-virt.il
  tailcall-rgctxa.il
  tailcall-rgctxb.il
  tailcall-rgctxb-static.il
  tailcall-mrgctx.il
  tailcall/interface-conservestack/1.il
  tailcall/interface-conservestack/10.il
  tailcall/interface-conservestack/11.il
  tailcall/interface-conservestack/12.il
  tailcall/interface-conservestack/13.il
  tailcall/interface-conservestack/14.il
  tailcall/interface-conservestack/15.il
  tailcall/interface-conservestack/16.il
  tailcall/interface-conservestack/17.il
  tailcall/interface-conservestack/18.il
  tailcall/interface-conservestack/19.il
  tailcall/interface-conservestack/2.il
  tailcall/interface-conservestack/20.il
  tailcall/interface-conservestack/21.il
  tailcall/interface-conservestack/22.il
  tailcall/interface-conservestack/23.il
  tailcall/interface-conservestack/24.il
  tailcall/interface-conservestack/25.il
  tailcall/interface-conservestack/26.il
  tailcall/interface-conservestack/27.il
  tailcall/interface-conservestack/28.il
  tailcall/interface-conservestack/29.il
  tailcall/interface-conservestack/3.il
  tailcall/interface-conservestack/30.il
  tailcall/interface-conservestack/31.il
  tailcall/interface-conservestack/32.il
  tailcall/interface-conservestack/33.il
  tailcall/interface-conservestack/34.il
  tailcall/interface-conservestack/35.il
  tailcall/interface-conservestack/36.il
  tailcall/interface-conservestack/37.il
  tailcall/interface-conservestack/38.il
  tailcall/interface-conservestack/39.il
  tailcall/interface-conservestack/4.il
  tailcall/interface-conservestack/40.il
  tailcall/interface-conservestack/41.il
  tailcall/interface-conservestack/42.il
  tailcall/interface-conservestack/43.il
  tailcall/interface-conservestack/44.il
  tailcall/interface-conservestack/45.il
  tailcall/interface-conservestack/46.il
  tailcall/interface-conservestack/47.il
  tailcall/interface-conservestack/48.il
  tailcall/interface-conservestack/49.il
  tailcall/interface-conservestack/5.il
  tailcall/interface-conservestack/50.il
  tailcall/interface-conservestack/51.il
  tailcall/interface-conservestack/52.il
  tailcall/interface-conservestack/53.il
  tailcall/interface-conservestack/6.il
  tailcall/interface-conservestack/7.il
  tailcall/interface-conservestack/8.il
  tailcall/interface-conservestack/9.il
  tailcall-interface-justrun.il
  field-access.il
  method-access.il
  ldftn-access.il
  cpblkTest.il
  vbinterface.il
  calliTest.il
  calliGenericTest.il
  ckfiniteTest.il
  interp-float-conv.il
  fault-handler.il
  locallocTest.il
  initblkTest.il
  qt-instance.il
  vararg3.il
  bug-29859.il
  bug-78549.il
  static-fields-nonconst.il
  reload-at-bb-end.il
  test-enum-indstoreil.il
  filter-bug.il
  even-odd.il
  bug-82022.il
  vt-sync-method.il
  enum_types.il
  invalid-token.il
  call_missing_method.il
  call_missing_class.il
  calli_sig_check.il
  ldfld_missing_field.il
  ldfld_missing_class.il
  find-method.2.il
  bug-79215.2.il
  bug-79956.2.il
  bug-327438.2.il
  bug-387274.2.il
  bug-426309.2.il
  ldtoken_with_byref_typespec.2.il
  resolve_method_bug.2.il
  resolve_field_bug.2.il
  resolve_type_bug.2.il
  generics-sharing-other-exc.2.il
  generic-ldobj.2.il
  generic-mkrefany.2.il
  generic-refanyval.2.il
  generic-ldtoken.2.il
  generic-ldtoken-method.2.il
  generic-ldtoken-field.2.il
  generic-tailcall.2.il
  generic-tailcall2.2.il
  generic-array-exc.2.il
  generic-valuetype-newobj2.2.il
  generic-valuetype-newobj.2.il
  generic-constrained.2.il
  generic-type-load-exception.2.il
  bug-81466.il
  bug457574.il
  bug445361.il
  bug-463303.il
  bug469742.2.il
  bug-528055.il
  array_load_exception.il
  bug-481403.il
  interface-with-static-method.il
  bug-633291.il
  delegate-with-null-target.il
  bug-318677.il
  gsharing-valuetype-layout.il
  invalid_generic_instantiation.il
  bug-45841-fpstack-exceptions.il
  instance_tailrec.il
  dim-constrainedcall.il
  dim-constrained3.il
  dim-constrained3_gm.il
  dim-diamondshape.il
  dim-genericmethods.il
  dim-methodimpl.il
  dim-sharedgenerics.il
  dim-simple.il
  dim-valuetypes.il
  dim-nested-types.il
  dim-generic-interface.il
  dim-implements-multiple-interfaces.il
  dim-sealed.il
  dim-protected-accessibility1.il
  dim-protected-accessibility2.il
  dim-reabstraction.il
  dim-reabstraction-generics.il
  dim-abstractcall.il
  twopassvariance.il
  tailcall-generic-cast-conservestack-il.il
  tailcall-generic-cast-nocrash-il.il
  tailcall-member-function-in-valuetype.il
  tailcall-return-valuetype.il
  tailcall-return-valuetype-deep.il
  tailcall-valuetype-parameter.il
  ldfldvt.il
  newobj-abstract.il
  invalid-isbyreflike.il
  custom-modifiers-append.1.il
  gh-13056_mono_local_cprop_av.il
  gh-13057_mono_local_emulate_ops_av.il
  module-cctor-entrypoint.il
  bug-gh-9706.il
  localloc-noinit.il
  volatile-prefix-shapes.il
  calli_native.il
)

# Microbenchmarks. They go into the `runtime` suite with the other corpora, so
# a pass says the program is correct, not that it is fast.
set(MONO_TESTS_BENCH_SRC
  fib.cs
  random.cs
  nested-loops.cs
  ackermann.cs
  tight-loop.cs
  sieve.cs
)

# Generic sharing. Run four times over different -O=gshared combinations.
set(MONO_TESTS_GSHARED_SRC
  generics-sharing.2.cs
  shared-generic-methods.2.cs
  shared-generic-synchronized.2.cs
  generic-initobj.2.cs
  generics-sharing-other-exc.2.cs
  generic-box.2.cs
  generic-unbox.2.cs
  generic-delegate.2.cs
  generic-sizeof.2.cs
  generic-ldobj.2.cs
  generic-mkrefany.2.cs
  generic-refanyval.2.cs
  generic-ldtoken.2.cs
  generic-ldtoken-method.2.cs
  generic-ldtoken-field.2.cs
  generic-virtual.2.cs
  generic-tailcall.2.cs
  generic-interface-methods.2.cs
  generic-array-type.2.cs
  generic-method-patching.2.cs
  generic-static-methods.2.cs
  generic-null-call.2.cs
  generic-tailcall2.2.cs
  generic-array-exc.2.cs
  generic-special.2.cs
  generic-special2.2.cs
  generic-exceptions.2.cs
  generic-delegate2.2.cs
  generic-virtual2.2.cs
  generic-valuetype-interface.2.cs
  generic-valuetype-newobj.2.cs
  generic-valuetype-newobj2.2.cs
  generic-getgenericarguments.2.cs
  generic-synchronized.2.cs
  generic-delegate-ctor.2.cs
  generic-constrained.2.cs
  bug-431413.2.cs
  generic-virtual-invoke.2.cs
  generic-typedef.2.cs
  generic-marshalbyref.2.cs
  bug-459285.2.cs
  bug-461198.2.cs
  generic-sealed-virtual.2.cs
  generic-system-arrays.2.cs
  generic-stack-traces.2.cs
  generic-stack-traces2.2.cs
  bug-472600.2.cs
  bug-473482.2.cs
  bug-473999.2.cs
  bug-479763.2.cs
  generic-type-load-exception.2.cs
  bug-616463.cs
  bug-1147.cs
  generic-type-builder.2.cs
)

# Long-running stress tests, kept out of the default suite.
set(MONO_TESTS_STRESS_SRC
  abort-stress-1.cs
  abort-stress-2.cs
  abort-stress-3.cs
  domain-stress.cs
  gchandle-stress.cs
  monitor-stress.cs
  thread-stress.cs
  gc-stress.cs
  gc-copy-stress.cs
  gc-graystack-stress.cs
  exit-stress.cs
  process-stress.cs
  spinlock-stress.cs
)

# Process-creation stress. Slow enough to need its own timeout.
set(MONO_TESTS_STRESS_PROCESS_SRC
  process-stress-1.cs
  process-stress-2.cs
  process-stress-3.cs
  process-leak.cs
)

# SGen tests, run once per collector configuration (see the matrix in
# CMakeLists.txt).
set(MONO_TESTS_SGEN_REGULAR_SRC
  finalizer-wait.cs
  critical-finalizers.cs
  sgen-descriptors.cs
  sgen-gshared-vtype.cs
  sgen-weakref-stress.cs
  sgen-cementing-stress.cs
  sgen-case-23400.cs
  sgen-new-threads-dont-join-stw.cs
  sgen-new-threads-dont-join-stw-2.cs
  sgen-new-threads-collect.cs
  gc-graystack-stress.cs
  bug-17590.cs
  sgen-domain-unload.cs
  sgen-domain-unload-2.cs
)

set(MONO_TESTS_SGEN_TOGGLEREF_SRC
  sgen-toggleref.cs
)

set(MONO_TESTS_SGEN_BRIDGE_SRC
  sgen-bridge.cs
  sgen-bridge-major-fragmentation.cs
)

set(MONO_TESTS_SGEN_BRIDGE2_SRC
  sgen-bridge-xref.cs
)

set(MONO_TESTS_SGEN_BRIDGE3_SRC
  sgen-bridge-gchandle.cs
)

set(MONO_TESTS_SGEN_OOM_SRC
  sgen-oom-cementing-stress.cs
  sgen-oom-new-threads-dont-join-stw-2.cs
  sgen-oom-bridge-major-fragmentation.cs
  gc-oom-handling.cs
  gc-oom-handling2.cs
)

# Tests whose whole point is the process exit code.
set(MONO_TESTS_UNHANDLED_EXCEPTION_1_SRC
  unhandled-exception-1.cs
  unhandled-exception-9.cs
)

set(MONO_TESTS_UNHANDLED_EXCEPTION_255_SRC
  unhandled-exception-2.cs
  unhandled-exception-3.cs
  unhandled-exception-4.cs
  unhandled-exception-5.cs
  unhandled-exception-6.cs
  unhandled-exception-7.cs
  unhandled-exception-8.cs
  threadpool-exceptions2.cs
  threadpool-exceptions5.cs
)

# A thread leaving managed code through a forced unwind. The exit code is what
# says the process got to the end rather than aborting in a personality routine.
set(MONO_TESTS_FORCED_UNWIND_SRC
  thread-forced-unwind.cs
)

# An exception caught above two interpreted frames rather than one. Which
# methods are interpreted has to be pinned rather than left to promotion, so
# this runs in a suite of its own with MONO_LLVM_JIT_TIER0 naming them.
set(MONO_TESTS_TIER_PINNED_SRC
  handle-stack-tiers.cs
  typedbyref-tier-entry.cs
)

# The same pinning, for a test whose calli has to be written by hand.
set(MONO_TESTS_TIER_PINNED_IL_SRC
  bug-unity-2.il
)

# The tier-2 cost model, which needs its root to gather counts at tier 1 and
# then be compiled at tier 2 exactly once. A threshold of zero leaves the body
# instrumented and counting while it never promotes on its own, so the compile
# the test asks for is the only one there is.
set(MONO_TESTS_TIER2_COSTED_SRC
  tier2-inline-cost.cs
)

# The tailcall suite, including the corpus imported from coreclr.
set(MONO_TESTS_TAILCALL_CS_SRC
  tailcall/coreclr/JIT/CodeGenBringUpTests/RecursiveTailCall.cs
  tailcall/coreclr/JIT/Methodical/tailcall/Desktop/thread-race.cs
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateParamCallTarget.cs
  tailcall/coreclr/JIT/opt/FastTailCall/FastTailCallCandidates.cs
  tailcall/coreclr/JIT/opt/FastTailCall/FastTailCallInlining.cs
  tailcall/coreclr/JIT/opt/FastTailCall/GitHubIssue12479.cs
  tailcall/coreclr/JIT/opt/FastTailCall/StackFixup.cs
  tailcall/coreclr/JIT/opt/FastTailCall/StructPassingSimple.cs
)

set(MONO_TESTS_TAILCALL_IL_SRC
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyWithPrefix.il
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyTransparentLibraryWithPrefix.il
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyVerifiableLibraryWithPrefix.il
  tailcall/coreclr/JIT/Directed/coverage/importer/badtailcall.il
  tailcall/coreclr/JIT/Directed/coverage/importer/Desktop/badtailcall.il
  tailcall/coreclr/JIT/Directed/IL/mutualrecur-tailcall/MutualRecur-TailCall.il
  tailcall/coreclr/JIT/Directed/IL/PInvokeTail/tailwinapi.il
  tailcall/coreclr/JIT/Directed/IL/Tailcall/JitTailcall1.il
  tailcall/coreclr/JIT/Directed/IL/Tailcall/Jittailcall2.il
  tailcall/coreclr/JIT/Directed/pinvoke/tail.il
  tailcall/coreclr/JIT/Directed/tailcall/tailcall.il
  tailcall/coreclr/JIT/IL_Conformance/Old/Base/tailcall.il
  tailcall/coreclr/JIT/Methodical/Boxing/boxunbox/tailcall.il
  tailcall/coreclr/JIT/Methodical/Boxing/misc/tailjump.il
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_call.il
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_calli.il
  tailcall/coreclr/JIT/Methodical/Invoke/SEH/catchfault_tail.il
  tailcall/coreclr/JIT/Methodical/Invoke/SEH/catchfinally_tail.il
  tailcall/coreclr/JIT/Methodical/nonvirtualcall/tailcall.il
  tailcall/coreclr/JIT/Methodical/tailcall/compat_obj.il
  tailcall/coreclr/JIT/Methodical/tailcall/compat_v.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array_nz.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_gc.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_inst.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_value.il
  tailcall/coreclr/JIT/Methodical/tailcall/deep_virt.il
  tailcall/coreclr/JIT/Methodical/tailcall/gcval.il
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_nested.il
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_sideeffect.il
  tailcall/coreclr/JIT/Methodical/tailcall/pointer.il
  tailcall/coreclr/JIT/Methodical/tailcall/pointer_i.il
  tailcall/coreclr/JIT/Methodical/tailcall/recurse_ep.il
  tailcall/coreclr/JIT/Methodical/tailcall/recurse_ep_void.il
  tailcall/coreclr/JIT/Methodical/tailcall/reference_i.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_2a.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_2b.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_2c.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_3b.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_implicit.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_mutual_rec.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_switch.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_virt.il
  tailcall/coreclr/JIT/Methodical/tailcall/test_void.il
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateTail.il
  tailcall/coreclr/JIT/Methodical/tailcall_v4/hijacking.il
  tailcall/coreclr/JIT/Methodical/tailcall_v4/smallFrame.il
  tailcall/coreclr/JIT/Methodical/tailcall_v4/tailcall_AV.il
  tailcall/coreclr/JIT/opt/ETW/TailCallCases.il
  tailcall/coreclr/JIT/Regression/VS-ia64-JIT/V1.2-M02/b102844/tailcallcalli.il
)

# Known-failing or not-applicable tests, excluded from every suite.
# automake accumulated this from three lists that overlapped; deduplicated.
set(MONO_TESTS_DISABLED
  delegate-async-exception.exe
  bug-348522.2.exe
  bug-459094.exe
  delegate-invoke.exe
  bug-Xamarin-5278.exe
  appdomain-marshalbyref-assemblyload.exe
  abort-try-holes.exe
  threads-init.exe
  gptail1.exe
  itaili1.exe
  sirtail1.exe
  srtail1.exe
  stail1.exe
  tail1.exe
  taili1.exe
  vtail1.exe
  tailcall-member-function-in-valuetype.exe
  tailcall-rgctxb.exe
  recursive-struct-arrays.exe
  tailcall/coreclr/JIT/Directed/IL/PInvokeTail/tailwinapi.exe
  tailcall/coreclr/JIT/Directed/IL/Tailcall/Jittailcall2.exe
  tailcall/coreclr/JIT/Directed/IL/mutualrecur-tailcall/MutualRecur-TailCall.exe
  tailcall/coreclr/JIT/Directed/coverage/importer/Desktop/badtailcall.exe
  tailcall/coreclr/JIT/Directed/coverage/importer/badtailcall.exe
  tailcall/coreclr/JIT/Directed/pinvoke/tail.exe
  tailcall/coreclr/JIT/IL_Conformance/Old/Base/tailcall.exe
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_call.exe
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_calli.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array_nz.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_nested.exe
  tailcall/coreclr/JIT/Methodical/tailcall/pointer_i.exe
  tailcall/coreclr/JIT/Methodical/tailcall/pointer.exe
  tailcall/coreclr/JIT/Methodical/tailcall/reference_i.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_implicit.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_mutual_rec.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_switch.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateTail.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/hijacking.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/smallFrame.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/tailcall_AV.exe
  tailcall/coreclr/JIT/Regression/VS-ia64-JIT/V1.2-M02/b102844/tailcallcalli.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyWithPrefix.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyTransparentLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyVerifiableLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/ETW/TailCallCases.exe
  tailcall/coreclr/JIT/Methodical/Boxing/misc/tailjump.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_gc.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_inst.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_value.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_virt.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_sideeffect.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_3b.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateParamCallTarget.exe
  merp-json-valid.exe
  merp-crash-test.exe
  finally_guard.exe
  # Scrapes "converting method ..." out of a --compile-all run. Neither the
  # option nor that trace exists any more.
  verbose.exe
)

# Additionally excluded when running under the interpreter.
set(MONO_TESTS_INTERP_DISABLED
  # The two below are the same interpreter defects MONO_TESTS_TIER0_DISABLED
  # names, and the reasons are written there. They fail here for the same
  # reason: the engine is the interpreter either way.
  interp-threadstatic-cctor.exe
  interp-array-set-typecheck.exe
  # With the interpreter as the whole engine there is no compiled tier, so the
  # address handed out is the interpreter's own entry and no jit call can be made
  # to go through it. A patch written over that address cannot take effect.
  interp-native-detour.exe
  delegate-async-exception.exe
  bug-348522.2.exe
  bug-459094.exe
  delegate-invoke.exe
  bug-Xamarin-5278.exe
  appdomain-marshalbyref-assemblyload.exe
  abort-try-holes.exe
  threads-init.exe
  recursive-struct-arrays.exe
  merp-json-valid.exe
  merp-crash-test.exe
  finally_guard.exe
  bug-60843.exe
  calli_sig_check.exe
  dim-diamondshape.exe
  pinvoke3.exe
  cominterop.exe
  ccw-class-iface.exe
  bug-60862.exe
  bug-48015.exe
)

# Additionally excluded at the default tier, where a method starts interpreted
# and is compiled underneath its callers once it is hot.
#
# Each of these passes with everything compiled and fails both here and under
# --interpreter, so what they are missing is something the interpreter does not
# do rather than anything about the tier seam. Say which, per entry: the point
# of this list being separate from MONO_TESTS_INTERP_DISABLED is that "tier 0
# cannot do this" and "the pure interpreter could not" are different claims.
set(MONO_TESTS_TIER0_DISABLED
  # A COM-visible call reaches Object::Equals through a remoting-invoke wrapper,
  # which answers "The method or operation is not implemented".
  cominterop.exe
  # calli does not check the signature it is handed. The test wants the
  # mismatched call to throw and gets a return.
  calli_sig_check.exe
  # A default-interface diamond resolves to one of the implementations where
  # the ambiguity is meant to raise.
  dim-diamondshape.exe
  # Reading a thread-static does not run the class initializer. The
  # special-static path carries the field's offset and no vtable, so nothing on
  # it can run one. ECMA-335 II.10.5.3.
  interp-threadstatic-cctor.exe
  # Storing into a multidimensional array checks the call site's static element
  # type rather than the value, so a Derived is refused by a Derived[,] that is
  # held in a Base[,] variable.
  interp-array-set-typecheck.exe
  # Overflows a thread's stack on purpose and wants a StackOverflowException
  # back. The interpreter does not recurse for a managed call, but it allocas
  # an InterpFrame for every new depth, so the native stack runs out anyway and
  # the fault lands in unmanaged code where it cannot become a managed
  # exception. Not the engine-alternation path: identical with tier 1 disabled.
  bug-60862.exe
)

# Not tests: source files that another tailcall test links against.
set(MONO_TESTS_TAILCALL_DISABLED_COMPILE
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyTransparentLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyVerifiableLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/ETW/TailCallCases.exe
)

# Tailcall tests that build but do not pass. Some read like negative tests
# that were never automated.
set(MONO_TESTS_TAILCALL_DISABLED_RUN
  tailcall/coreclr/JIT/Directed/IL/PInvokeTail/tailwinapi.exe
  tailcall/coreclr/JIT/Directed/IL/Tailcall/Jittailcall2.exe
  tailcall/coreclr/JIT/Directed/IL/mutualrecur-tailcall/MutualRecur-TailCall.exe
  tailcall/coreclr/JIT/Directed/coverage/importer/Desktop/badtailcall.exe
  tailcall/coreclr/JIT/Directed/coverage/importer/badtailcall.exe
  tailcall/coreclr/JIT/Directed/pinvoke/tail.exe
  tailcall/coreclr/JIT/IL_Conformance/Old/Base/tailcall.exe
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_call.exe
  tailcall/coreclr/JIT/Methodical/Invoke/fptr/recurse_tail_calli.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_array_nz.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_nested.exe
  tailcall/coreclr/JIT/Methodical/tailcall/pointer_i.exe
  tailcall/coreclr/JIT/Methodical/tailcall/pointer.exe
  tailcall/coreclr/JIT/Methodical/tailcall/reference_i.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_implicit.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_mutual_rec.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_switch.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateTail.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/hijacking.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/smallFrame.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/tailcall_AV.exe
  tailcall/coreclr/JIT/Regression/VS-ia64-JIT/V1.2-M02/b102844/tailcallcalli.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyWithPrefix.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyTransparentLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/Tailcall/TailcallVerifyVerifiableLibraryWithPrefix.exe
  tailcall/coreclr/JIT/opt/ETW/TailCallCases.exe
  tailcall/coreclr/JIT/Methodical/Boxing/misc/tailjump.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_gc.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_inst.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_value.exe
  tailcall/coreclr/JIT/Methodical/tailcall/deep_virt.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval.exe
  tailcall/coreclr/JIT/Methodical/tailcall/gcval_sideeffect.exe
  tailcall/coreclr/JIT/Methodical/tailcall/test_3b.exe
  tailcall/coreclr/JIT/Methodical/tailcall_v4/delegateParamCallTarget.exe
  # prints PASS and then returns CoreCLR's 100-means-success, which this
  # harness reads as a failure
  tailcall/coreclr/JIT/Methodical/tailcall/Desktop/thread-race.exe
)


# Tests kept off the boehm half, so only `<test>@sgen` runs.
set(MONO_TESTS_BOEHM_DISABLED
  # Boehm does not support weak fields
  weak-fields.exe
  # currently hangs
  thread-suspend-suspended.exe
  # this test does not run correctly under a conservative gc
  monitor-resurrection.exe
)

# The interpreter runs on Boehm too, and the same three come off that half.