# Splits one class-library test assembly into groups, at build time.
#
# Run as `cmake -D SETTINGS=<file> -P MonoBclDiscover.cmake` from a custom
# command that depends on the test assembly, so the listing happens once per
# build rather than once per `ctest`.  What it writes is a small CMake file
# naming each group and the runner arguments that select it.
# MonoBclTests.cmake.in reads that and does the add_test() calls.
#
# Every failure path here writes an empty group list, which the template reads
# as "run the assembly whole".  A suite that cannot be listed -- because the
# runtime being built cannot get that far, which is normal on this branch --
# has to keep building and keep testing, not break the build.
#
# Routine progress is not printed at all.  Ninja merges a command's stdout and
# stderr into its own stdout, so this script has nowhere to print progress
# without it landing in the build log.  A successful split records how it went
# as comments in the group file instead, next to the groups it explains.
# Those comments stay there once the log has scrolled.
# MONO_BCL_DISCOVER_VERBOSE in the environment echoes them to stderr as well.
# A listing that *failed* is the one thing said unconditionally, because an
# unsplit suite is otherwise indistinguishable from one nobody asked to split.

cmake_minimum_required(VERSION 3.16)

if(NOT SETTINGS)
  message(FATAL_ERROR "MonoBclDiscover.cmake needs -D SETTINGS=<file>")
endif()
include("${SETTINGS}")

# Writes the group file and stops.  With no groups the suite stays whole.
function(_bcl_emit count)
  set(_text "# Generated by MonoBclDiscover.cmake -- do not edit.\n")
  foreach(_n IN LISTS _notes)
    # A note carrying the lister's stderr can be several lines. Folding it
    # keeps every one of them behind the `#`.
    string(REGEX REPLACE "[\r\n]+" " " _n "${_n}")
    string(APPEND _text "# ${BCL_TESTNAME}: ${_n}\n")
  endforeach()
  string(APPEND _text "set(BCL_GROUP_COUNT ${count})\n")
  if(count GREATER 0)
    math(EXPR _last "${count} - 1")
    foreach(_i RANGE ${_last})
      string(APPEND _text "set(BCL_GROUP_${_i}_NAME [==[${_outname_${_i}}]==])\n")
      string(APPEND _text "set(BCL_GROUP_${_i}_ARGS [==[${_outargs_${_i}}]==])\n")
    endforeach()
  endif()
  string(APPEND _text "set(BCL_CATCHALL_ARGS [==[${_catchall}]==])\n")
  file(WRITE "${BCL_OUTPUT}" "${_text}")
endfunction()

# Records how the split came out, for the group file _bcl_emit is about to write.
set(_notes "")
macro(_bcl_note text)
  list(APPEND _notes "${text}")
  if(NOT "$ENV{MONO_BCL_DISCOVER_VERBOSE}" STREQUAL "")
    message(NOTICE "${BCL_TESTNAME}: ${text}")
  endif()
endmacro()

macro(_bcl_give_up why)
  list(APPEND _notes "not split (${why})")
  message(WARNING "${BCL_TESTNAME}: not split (${why})")
  set(_catchall "")
  _bcl_emit(0)
  return()
endmacro()

# Run the lister
file(REMOVE "${BCL_LISTING}")

# nunit-lite writes its tree to the file -explore names. The xunit lister
# prints to stdout, so that is where the file comes from.
if(BCL_KIND STREQUAL xunit)
  set(_stdout OUTPUT_FILE "${BCL_LISTING}")
else()
  set(_stdout OUTPUT_QUIET)
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env ${BCL_ENVIRONMENT} -- ${BCL_LISTER_COMMAND}
  WORKING_DIRECTORY "${BCL_WORKDIR}"
  ${_stdout} ERROR_VARIABLE _err
  RESULT_VARIABLE _rc TIMEOUT 600)

if(NOT _rc EQUAL 0)
  _bcl_give_up("lister exited ${_rc}: ${_err}")
endif()
if(NOT EXISTS "${BCL_LISTING}")
  _bcl_give_up("lister wrote no listing")
endif()

# Read the listing into (name, weight) pairs
# A name is whatever the runner's own filter matches: a fixture's full name for
# nunit-lite, a class's full name for xunit.  The weight is what that name is
# worth -- cases for nunit, which knows, and one apiece for xunit, which does
# not.
set(_names "")
set(_weights "")

if(BCL_KIND STREQUAL nunit)
  # nunit-lite's -explore tree.  Every case sits under a TestFixture, and the
  # count on the root element is what proves it.
  file(STRINGS "${BCL_LISTING}" _lines REGEX "<test-suite type=\"(Assembly|TestFixture)\"")
  set(_total -1)
  set(_sum 0)
  foreach(_l IN LISTS _lines)
    if(NOT _l MATCHES "fullname=\"([^\"]*)\".*testcasecount=\"([0-9]+)\"")
      _bcl_give_up("unparsable listing line: ${_l}")
    endif()
    set(_name "${CMAKE_MATCH_1}")
    set(_count "${CMAKE_MATCH_2}")
    if(_l MATCHES "type=\"Assembly\"")
      set(_total "${_count}")
    else()
      list(APPEND _names "${_name}")
      list(APPEND _weights "${_count}")
      math(EXPR _sum "${_sum} + ${_count}")
    endif()
  endforeach()
  if(_total LESS 0)
    _bcl_give_up("listing has no assembly element")
  endif()
  if(NOT _sum EQUAL _total)
    _bcl_give_up("fixtures hold ${_sum} of ${_total} cases; something is not under a fixture")
  endif()
else()
  file(STRINGS "${BCL_LISTING}" _names)
  foreach(_n IN LISTS _names)
    list(APPEND _weights 1)
  endforeach()
endif()

list(LENGTH _names _items)
if(_items LESS 2)
  _bcl_give_up("${_items} groupable item(s)")
endif()

# A name has to survive a CMake list, a generated file and a command line
# untouched. No suite here needs anything outside that set, so this script
# refuses a name rather than mangling it to fit.
foreach(_n IN LISTS _names)
  if(NOT _n MATCHES "^[A-Za-z0-9_.+`]+$")
    _bcl_give_up("name is not plain: ${_n}")
  endif()
endforeach()

# Group by namespace
# Returns the group name for name: every leading `.`-separated segment but
# the last.
function(_bcl_namespace_of out name)
  if(NOT name MATCHES "\\.")
    set(${out} "global" PARENT_SCOPE)
    return()
  endif()
  string(REGEX REPLACE "\\.[^.]+$" "" _ns "${name}")
  set(${out} "${_ns}" PARENT_SCOPE)
endfunction()

# Groups are held as parallel _gname_<i> / _gmembers_<i> / _gweight_<i>, with
# _gkeys the list of namespaces in index order so one can be looked up.
set(_gkeys "")
set(_gcount 0)
math(EXPR _last "${_items} - 1")
foreach(_i RANGE ${_last})
  list(GET _names ${_i} _name)
  list(GET _weights ${_i} _w)
  _bcl_namespace_of(_key "${_name}")
  list(FIND _gkeys "${_key}" _g)
  if(_g LESS 0)
    set(_g ${_gcount})
    list(APPEND _gkeys "${_key}")
    set(_gname_${_g} "${_key}")
    set(_gmembers_${_g} "")
    set(_gweight_${_g} 0)
    math(EXPR _gcount "${_gcount} + 1")
  endif()
  list(APPEND _gmembers_${_g} "${_name}")
  math(EXPR _gweight_${_g} "${_gweight_${_g}} + ${_w}")
  set(_groupof_${_i} ${_g})
endforeach()

# _gdead_<i> marks a group folded into another. _glive() follows the chain.
function(_glive out g)
  while(DEFINED _gdead_${g})
    set(g "${_gdead_${g}}")
  endwhile()
  set(${out} ${g} PARENT_SCOPE)
endfunction()

# nunit only: names that are prefixes of each other cannot be separated
# nunit-lite's -test: filter matches with StartsWith on this runtime, so naming
# `System.DecimalTest` also selects `System.DecimalTest2`.  Inside one group
# that is harmless -- both were going to run there.  Across two it would run the
# longer one twice, so those two groups become one.
if(BCL_KIND STREQUAL nunit)
  # Once sorted, the names a given name prefixes form the run right after it,
  # so the scan stops at the first non-match.
  set(_order "")
  foreach(_i RANGE ${_last})
    list(GET _names ${_i} _n)
    list(APPEND _order "${_n}\t${_i}")
  endforeach()
  list(SORT _order)
  foreach(_i RANGE ${_last})
    list(GET _order ${_i} _a)
    string(REGEX REPLACE "\t.*$" "" _aname "${_a}")
    string(REGEX REPLACE "^.*\t" "" _ai "${_a}")
    string(LENGTH "${_aname}" _alen)
    math(EXPR _j "${_i} + 1")
    while(_j LESS_EQUAL ${_last})
      list(GET _order ${_j} _b)
      string(REGEX REPLACE "\t.*$" "" _bname "${_b}")
      string(LENGTH "${_bname}" _blen)
      if(_blen LESS ${_alen})
        break()
      endif()
      string(SUBSTRING "${_bname}" 0 ${_alen} _head)
      if(NOT _head STREQUAL "${_aname}")
        break()
      endif()
      string(REGEX REPLACE "^.*\t" "" _bi "${_b}")
      _glive(_ga ${_groupof_${_ai}})
      _glive(_gb ${_groupof_${_bi}})
      if(NOT _ga EQUAL _gb)
        list(APPEND _gmembers_${_ga} ${_gmembers_${_gb}})
        math(EXPR _gweight_${_ga} "${_gweight_${_ga}} + ${_gweight_${_gb}}")
        set(_gdead_${_gb} ${_ga})
        set(_reason "${_aname} also selects ${_bname}")
        _bcl_note("${_gname_${_gb}} folded into ${_gname_${_ga}} (${_reason})")
      endif()
      math(EXPR _j "${_j} + 1")
    endwhile()
  endforeach()
endif()

set(_live "")
math(EXPR _glast "${_gcount} - 1")
foreach(_g RANGE ${_glast})
  if(NOT DEFINED _gdead_${_g})
    list(APPEND _live ${_g})
  endif()
endforeach()

# xunit with a quarantine list: cut for isolation rather than for throughput
# A suite whose collections run concurrently in one console wants the opposite
# of a split: everything in a single process, since each extra one costs ~45s of
# runner JIT before a case runs.  What it still cannot do is share that process
# with a namespace that has to run on its own.
#
# So the named namespaces get a process each and everything else runs as their
# complement -- which is why there is no catch-all here.  `-noclass` covers a
# class the lister never saw as well, so nothing can fall out of the suite the
# way it could if the remainder were spelled out class by class.
#
# nunit has no counterpart: `-test:` selects, and there is nothing that excludes
# a fixture by name, so the remainder cannot be expressed.
if(BCL_QUARANTINE AND BCL_KIND STREQUAL xunit)
  set(_kept "")
  set(_excluded "")
  foreach(_g IN LISTS _live)
    list(FIND BCL_QUARANTINE "${_gname_${_g}}" _q)
    if(NOT _q LESS 0)
      list(APPEND _kept ${_g})
      list(APPEND _excluded ${_gmembers_${_g}})
    endif()
  endforeach()

  # An entry naming a namespace this assembly does not have otherwise has no
  # effect, indistinguishable from that namespace never needing isolation.
  foreach(_q IN LISTS BCL_QUARANTINE)
    list(FIND _gkeys "${_q}" _at)
    if(_at LESS 0)
      _bcl_note("quarantine names ${_q}, which no class here is in")
      message(WARNING "${BCL_TESTNAME}: quarantine names ${_q}, which no class here is in")
    endif()
  endforeach()

  set(_out 0)
  foreach(_g IN LISTS _kept)
    set(_args "")
    foreach(_m IN LISTS _gmembers_${_g})
      list(APPEND _args "-class" "${_m}")
    endforeach()
    set(_outname_${_out} "${_gname_${_g}}")
    set(_outargs_${_out} "${_args}")
    math(EXPR _out "${_out} + 1")
  endforeach()

  set(_args "")
  foreach(_m IN LISTS _excluded)
    list(APPEND _args "-noclass" "${_m}")
  endforeach()
  set(_outname_${_out} "rest")
  set(_outargs_${_out} "${_args}")
  math(EXPR _out "${_out} + 1")

  set(_catchall "")
  list(LENGTH _excluded _nq)
  _bcl_note("${_items} items, ${_nq} of them quarantined into ${_out} groups")
  _bcl_emit(${_out})
  return()
endif()

# Cap the group count
# Each group is a process, and a process is not free: nunit-lite costs about 6s
# before it runs anything and xunit.console about 45s, nearly all of it JIT of
# the runner.  Past a point another group buys less than it costs, so the
# lightest groups are swept into one instead.
list(LENGTH _live _n)
if(BCL_MAX_GROUPS GREATER 0 AND _n GREATER ${BCL_MAX_GROUPS})
  set(_ranked "")
  foreach(_g IN LISTS _live)
    string(LENGTH "${_gweight_${_g}}" _wl)
    string(SUBSTRING "0000000000${_gweight_${_g}}" ${_wl} -1 _key)
    list(APPEND _ranked "${_key}\t${_g}")
  endforeach()
  list(SORT _ranked)
  list(REVERSE _ranked)

  math(EXPR _keep "${BCL_MAX_GROUPS} - 1")
  set(_rest "")
  set(_kept "")
  set(_i 0)
  foreach(_r IN LISTS _ranked)
    string(REGEX REPLACE "^.*\t" "" _g "${_r}")
    if(_i LESS ${_keep})
      list(APPEND _kept ${_g})
    else()
      list(APPEND _rest ${_gmembers_${_g}})
    endif()
    math(EXPR _i "${_i} + 1")
  endforeach()

  set(_g ${_gcount})
  math(EXPR _gcount "${_gcount} + 1")
  set(_gname_${_g} "other")
  set(_gmembers_${_g} ${_rest})
  list(APPEND _kept ${_g})
  set(_live ${_kept})
  _bcl_note("capped at ${BCL_MAX_GROUPS} groups")
endif()

# Turn the groups into runner arguments
# Every item is named in exactly one group, and the prefix folding above is what
# makes that hold for nunit's StartsWith filter too, so the groups are disjoint.
# The xunit half adds one more test excluding every class the lister found: it
# is the complement, so whatever the lister missed still runs, and it reports as
# a skip when there was nothing to miss.
set(_catchall "")
set(_out 0)
foreach(_g IN LISTS _live)
  set(_args "")
  foreach(_m IN LISTS _gmembers_${_g})
    if(BCL_KIND STREQUAL nunit)
      list(APPEND _args "-test:${_m}")
    else()
      list(APPEND _args "-class" "${_m}")
      list(APPEND _catchall "-noclass" "${_m}")
    endif()
  endforeach()
  set(_outname_${_out} "${_gname_${_g}}")
  set(_outargs_${_out} "${_args}")
  math(EXPR _out "${_out} + 1")
endforeach()

_bcl_note("${_items} items in ${_out} groups")
_bcl_emit(${_out})
