# Which mono hosts the build-time C# compiles.
#
# Everything managed that this build produces -- the test corpora, the little
# assemblies the unit tests load, the CoreCLR suites, the class libraries --
# is compiled by Roslyn (and assembled by ilasm), both of which are themselves
# managed programs and so need a mono to run on.  By default that is the mono
# this build produces, which is what the autotools build did and what a release
# build must keep doing: the compiler that builds the tests is then the same
# code the tests exercise.
#
# It is also the slow choice.  The in-tree runtime is an unoptimised build with
# the LLVM tier enabled, and hosting Roslyn on it costs roughly 4x what a
# released mono costs -- measured over twelve CoreMangLib tests, 54.5s in-tree
# against 12.5s on the system mono 6.8.  Worse, every compile is then downstream
# of the native link, so a one-line change in mono/mini rebuilds the runtime
# before any C# can be compiled at all.
#
# MONO_USE_SYSTEM_RUNTIME_FOR_TOOLS moves those compiles onto a mono already
# installed on the machine -- csc and the small programs around it alike
# (gensources, resgen, sn, ilasm, cil-stringreplacer).  Tests still *run* on the
# runtime being built -- that is the thing under test and it never moves.  Only
# the host the build's own tools run on changes.
#
# Moving all of them, not just csc, is what makes the option worth having: the
# class libraries are downstream of those tools, and every test corpus is
# downstream of the class libraries, so leaving one of them on the in-tree
# runtime puts the whole managed build back behind the native link.
#
#   cmake -B build -D MONO_USE_SYSTEM_RUNTIME_FOR_TOOLS=ON
#   cmake -B build -D MONO_USE_SYSTEM_RUNTIME_FOR_TOOLS=ON \
#                  -D MONO_SYSTEM_RUNTIME=/opt/mono/bin/mono-sgen
#
# The catch, and the reason this is off by default: the class libraries are
# compiled against whatever mscorlib the hosting runtime hands Roslyn when the
# compile does not name one itself.  mono/tests and acceptance-tests do not name
# one, so with this on they see the system mono's BCL surface rather than this
# tree's.  For the mini corpora and the class libraries it makes no difference --
# those compile -nostdlib against an explicit -r:.../mscorlib.dll.  Treat the
# option as an iteration aid.  Validate on a default configuration.

# What a build step that runs runtime/mono-wrapper has to wait for, rather than
# ${MONO_TOOLS_RUNTIME}.  The wrapper is a script around mono/mini/mono-<gc>, and
# some callers reach for the mono-<gc> symlink by name, so both have to exist
# first.  MONO_TOOLS_RUNTIME_DEPENDS does not cover such a step: it is empty when
# the tools run on the system mono.
set(MONO_INBUILD_RUNTIME_DEPENDS mono-${MONO_DEFAULT_GC_SUFFIX} mono-symlink)

if(MONO_USE_SYSTEM_RUNTIME_FOR_TOOLS)
  if(MONO_SYSTEM_RUNTIME)
    if(NOT EXISTS "${MONO_SYSTEM_RUNTIME}")
      message(FATAL_ERROR
        "MONO_SYSTEM_RUNTIME is set to '${MONO_SYSTEM_RUNTIME}', which does not exist")
    endif()
    set(_tools_mono "${MONO_SYSTEM_RUNTIME}")
  else()
    if(NOT MONO_SYSTEM_RUNTIME_EXECUTABLE)
      message(FATAL_ERROR
        "MONO_USE_SYSTEM_RUNTIME_FOR_TOOLS is on but no mono-sgen or mono was "
        "found on PATH.  Install one, or point MONO_SYSTEM_RUNTIME at it.")
    endif()
    set(_tools_mono "${MONO_SYSTEM_RUNTIME_EXECUTABLE}")
  endif()

  # Fail here rather than five thousand compile commands later.
  execute_process(COMMAND "${_tools_mono}" --version
                  OUTPUT_VARIABLE _v ERROR_VARIABLE _v
                  RESULT_VARIABLE _rc OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "'${_tools_mono} --version' failed:\n${_v}")
  endif()
  string(REGEX MATCH "version [0-9][^ ]*" MONO_TOOLS_RUNTIME_VERSION "${_v}")

  set(MONO_TOOLS_RUNTIME "${_tools_mono}")
  set(MONO_TOOLS_RUNTIME_IS_SYSTEM TRUE)
  set(MONO_TOOLS_RUNTIME_DEPENDS "")

  # What the build gets told to run its managed tools on.  It cannot be the
  # bare binary: mcs sets MONO_PATH to class/lib/build for every compile, and
  # that directory holds this tree's mscorlib.dll -- which a foreign runtime
  # refuses outright ("Corlib not in sync with this runtime ... Expected
  # interface version <its own> but found <ours>").  None of the tools need
  # MONO_PATH on a system mono.  Each resolves its dependencies out of its own
  # directory, or out of that runtime's own BCL.  So drop the variable on the
  # way through, wherever it came from.
  set(MONO_TOOLS_RUNTIME_HOST "${CMAKE_BINARY_DIR}/runtime/tools-mono")
  file(WRITE "${MONO_TOOLS_RUNTIME_HOST}"
"#! /bin/sh
# Generated by CMake -- do not edit.
# The build's managed tools run on a mono that is not the one this build
# produces, so MONO_PATH has to go: it points at mcs/class/lib/build, whose
# mscorlib.dll belongs to this tree and not to the runtime below, and mono
# rejects that pairing outright.
unset MONO_PATH
exec \"${_tools_mono}\" \"$@\"
")
  file(CHMOD "${MONO_TOOLS_RUNTIME_HOST}" PERMISSIONS
       OWNER_READ OWNER_WRITE OWNER_EXECUTE
       GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
else()
  set(MONO_TOOLS_RUNTIME "${MONO_RUNTIME_WRAPPER}")
  set(MONO_TOOLS_RUNTIME_IS_SYSTEM FALSE)
  set(MONO_TOOLS_RUNTIME_VERSION "this build")
  set(MONO_TOOLS_RUNTIME_DEPENDS ${MONO_INBUILD_RUNTIME_DEPENDS})
  set(MONO_TOOLS_RUNTIME_HOST "")
  # Turning the option back off in an existing tree otherwise leaves the shim
  # on disk, pointing at a runtime nothing runs on any more.
  file(REMOVE "${CMAKE_BINARY_DIR}/runtime/tools-mono")
endif()

# Spell out one invocation of a managed build tool.
#
#   mono_tools_runtime(<out> [MONO_PATH <dir>] [ARGS <arg>...])
#
# The result is a command prefix.  The caller appends the assembly to run and
# its arguments.  MONO_PATH describes what the *in-tree* runtime needs, and is
# dropped for a system one: keeping it there puts this tree's mscorlib.dll in
# front of the one that runtime was built against.
function(mono_tools_runtime out)
  cmake_parse_arguments(ARG "" "MONO_PATH" "ARGS" ${ARGN})
  if(MONO_TOOLS_RUNTIME_IS_SYSTEM)
    set(_cmd "${MONO_TOOLS_RUNTIME_HOST}" ${ARG_ARGS})
  else()
    set(_cmd "${CMAKE_COMMAND}" -E env)
    if(ARG_MONO_PATH)
      list(APPEND _cmd "MONO_PATH=${ARG_MONO_PATH}")
    endif()
    list(APPEND _cmd "${MONO_TOOLS_RUNTIME}")
    list(APPEND _cmd ${ARG_ARGS})
  endif()
  set(${out} "${_cmd}" PARENT_SCOPE)
endfunction()

# add_dependencies() on whatever the compiles need built first, which is
# nothing at all when they run on a runtime this build did not make.  A bare
# add_dependencies(t) with an empty list is an error, hence the wrapper.
function(mono_tools_runtime_depends target)
  if(MONO_TOOLS_RUNTIME_DEPENDS)
    add_dependencies(${target} ${MONO_TOOLS_RUNTIME_DEPENDS})
  endif()
endfunction()
