# mdoc's documentation round-trip suite: fifteen checks, each driven by
# mdoc-test.cmake.  The compiler command is written to a settings file rather
# than passed on the command line, because it is a list and add_test() has no
# way to carry one through as a single argument.
mono_profile_dir(_pdir net_4_x)
set(_src "${CMAKE_CURRENT_SOURCE_DIR}")
set(_settings "${CMAKE_CURRENT_BINARY_DIR}/mdoc-test-settings.cmake")

_mono_csc_command(_csc net_4_x)
_mono_csc_env(_cscenv net_4_x)
set(_cscmd ${_csc})
if(_cscenv)
  set(_cscmd "${CMAKE_COMMAND}" -E env ${_cscenv} ${_csc})
endif()

set(_runtime "${CMAKE_BINARY_DIR}/runtime/mono-wrapper")
file(CONFIGURE OUTPUT "${_settings}" CONTENT [[
# Generated by mcs/tools/mdoc/extra.cmake -- do not edit.
set(RUNTIME     [==[@_runtime@]==])
set(PROFILE_DIR [==[@_pdir@]==])
set(MDOC        [==[@_pdir@/mdoc.exe]==])
set(MDOC_CSC    [==[@_cscmd@]==])
set(MDOC_CSC_FLAGS [==[@MONO_MANAGED_COMMON_FLAGS@]==])
]] @ONLY)

set(_cases
    monodocer
    monodocer-since
    monodocer-delete
    monodocer-importslashdoc
    monodocer-importecmadoc
    monodocer-internal-interface
    monodocer-enumerations
    monodocer-dropns-classic
    monodocer-dropns-classic-withsecondary
    monodocer-dropns-multi
    monodocer-dropns-multi-withexisting
    mdoc-export-html
    mdoc-export-html-with-version
    mdoc-export-msxdoc
    mdoc-validate)

foreach(_case IN LISTS _cases)
  string(REGEX REPLACE "^mdoc-" "" _name "${_case}")
  add_test(NAME mdoc-${_name}
           COMMAND "${CMAKE_COMMAND}"
                   -D "SETTINGS=${_settings}"
                   -D "SRCDIR=${_src}"
                   -D "WORKDIR=${CMAKE_CURRENT_BINARY_DIR}/run/${_case}"
                   -D "CASE=${_case}"
                   -P "${_src}/mdoc-test.cmake")
  set_tests_properties(mdoc-${_name} PROPERTIES
    LABELS "tools" TIMEOUT 1800 FIXTURES_REQUIRED mdoc_tests)
endforeach()

add_custom_target(mcs-mdoc-tests)
add_dependencies(mcs-mdoc-tests mcs-net_4_x-mdoc mcs-net_4_x-Microsoft.CSharp)

add_test(NAME mdoc-tests-build
         COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_BINARY_DIR}"
                 --target mcs-mdoc-tests)
set_tests_properties(mdoc-tests-build PROPERTIES
  LABELS "fixture" TIMEOUT 1800 FIXTURES_SETUP mdoc_tests RESOURCE_LOCK ninja)
